#pragma once

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3.h>
#include <GLFW/glfw3native.h>
#endif

#include <unigui/backend/backend_factory.h>
#include <unigui/backend/backend_types.h>
#include <unigui/backend/platform_backend.h>
#include <unigui/backend/renderer_backend.h>
#include <unigui/core/api.h>
#include <unigui/core/context.h>
#include <unigui/core/decimate.h>
#include <unigui/core/error.h>
#include <unigui/core/format_cn.h>
#include <unigui/core/format_num.h>
#include <unigui/core/locale.h>
#include <unigui/core/log.h>
#include <unigui/core/main_thread.h>
#include <unigui/core/make.h>
#include <unigui/core/observable.h>
#include <unigui/core/scope.h>
#include <unigui/core/session_axis.h>
#include <unigui/core/settings.h>
#include <unigui/core/undo_stack.h>
#include <unigui/core/version.h>
#include <unigui/dsl/dsl.h>
#include <unigui/events/eventbus.h>
#include <unigui/ext/plot.h>
#include <unigui/fonts/font_manager.h>
#include <unigui/plugin/plugin_interface.h>
#include <unigui/plugin/plugin_manager.h>
#include <unigui/styling/style_engine.h>
#include <unigui/theme/color_tokens.h>
#include <unigui/theme/style_scope.h>
#include <unigui/theme/surface_style.h>
#include <unigui/theme/theme.h>
#include <unigui/widgets/alertbar.h>
#include <unigui/widgets/breadcrumb.h>
#include <unigui/widgets/button.h>
#include <unigui/widgets/checkbox.h>
#include <unigui/widgets/collapsingheader.h>
#include <unigui/widgets/coloredit.h>
#include <unigui/widgets/colorpicker.h>
#include <unigui/widgets/combobox.h>
#include <unigui/widgets/contextmenu.h>
#include <unigui/widgets/datepicker.h>
#include <unigui/widgets/dialog.h>
#include <unigui/widgets/dirpath.h>
#include <unigui/widgets/dragdrop.h>
#include <unigui/widgets/dragfloat.h>
#include <unigui/widgets/dragint.h>
#include <unigui/widgets/filepath.h>
#include <unigui/widgets/form.h>
#include <unigui/widgets/groupbox.h>
#include <unigui/widgets/hyperlink.h>
#include <unigui/widgets/iconbutton.h>
#include <unigui/widgets/image.h>
#include <unigui/widgets/inputfloat.h>
#include <unigui/widgets/inputint.h>
#include <unigui/widgets/inputtext.h>
#include <unigui/widgets/label.h>
#include <unigui/widgets/lineedit.h>
#include <unigui/widgets/listbox.h>
#include <unigui/widgets/listview.h>
#include <unigui/widgets/loadingindicator.h>
#include <unigui/widgets/menubar.h>
#include <unigui/widgets/multiline.h>
#include <unigui/widgets/notification.h>
#include <unigui/widgets/panel.h>
#include <unigui/widgets/panelbox.h>
#include <unigui/widgets/progressbar.h>
#include <unigui/widgets/radiogroup.h>
#include <unigui/widgets/riskbar.h>
#include <unigui/widgets/scrollarea.h>
#include <unigui/widgets/selectable.h>
#include <unigui/widgets/separator.h>
#include <unigui/widgets/shortcut.h>
#include <unigui/widgets/slider.h>
#include <unigui/widgets/space.h>
#include <unigui/widgets/spinbox.h>
#include <unigui/widgets/splitter.h>
#include <unigui/widgets/statusbar.h>
#include <unigui/widgets/table.h>
#include <unigui/widgets/tabwidget.h>
#include <unigui/widgets/tag.h>
#include <unigui/widgets/toggleswitch.h>
#include <unigui/widgets/toolbar.h>
#include <unigui/widgets/tooltip.h>
#include <unigui/widgets/treeview.h>
#include <unigui/widgets/value_widget.h>
#include <unigui/widgets/widget_base.h>
#include <unigui/widgets/window.h>
#ifdef UNIGUI_HAS_CONFIG
#include <unigui/config/config.h>
#endif
#ifdef UNIGUI_HAS_NETWORK
#include <unigui/network/network.h>
#endif
#ifdef UNIGUI_HAS_SQLITE
#include <unigui/sqlite/database.h>
#endif
#ifdef UNIGUI_HAS_IPC
#include <unigui/ipc/ipc.h>
#include <unigui/ipc/shmem.h>
#endif
#ifdef UNIGUI_HAS_TRADING
#include <unigui/trading/ohlc_series.h>
#include <unigui/trading/order_book.h>
#include <unigui/trading/quote.h>
// Trading widgets (presentation layer).
#include <unigui/trading/blotters.h>
#include <unigui/trading/candlestick_chart.h>
#include <unigui/trading/depth_ladder.h>
#include <unigui/trading/order_ticket.h>
#endif
#include <unigui/app/app.h>
#include <unigui/fonts/gradient_text.h>
#include <unigui/fx/animation.h>
#include <unigui/fx/easing.h>
#include <unigui/fx/effect_scope.h>
#include <unigui/fx/elevation.h>
#include <unigui/fx/transition.h>
#include <unigui/im/im.h>
#include <unigui/theme/presets/registry.h>
#include <unigui/widgets/animate.h>
#include <unigui/widgets/badge.h>
#include <unigui/widgets/basketticket.h>
#include <unigui/widgets/buttongroup.h>
#include <unigui/widgets/card.h>
#include <unigui/widgets/cascadingcombo.h>
#include <unigui/widgets/clipboard.h>
#include <unigui/widgets/confirmdialog.h>
#include <unigui/widgets/connection_status.h>
#include <unigui/widgets/datatable.h>
#include <unigui/widgets/editabledatagrid.h>
#include <unigui/widgets/futuresriskbar.h>
#include <unigui/widgets/gauge.h>
#include <unigui/widgets/groupedrisktree.h>
#include <unigui/widgets/herosection.h>
#include <unigui/widgets/layout.h>
#include <unigui/widgets/metriccard.h>
#include <unigui/widgets/multicombo.h>
#include <unigui/widgets/multihandleslider.h>
#include <unigui/widgets/multisplitter.h>
#include <unigui/widgets/passwordinput.h>
#include <unigui/widgets/pnltext.h>
#include <unigui/widgets/priceticker.h>
#include <unigui/widgets/propertygrid.h>
#include <unigui/widgets/searchbox.h>
#include <unigui/widgets/segmentedcontrol.h>
#include <unigui/widgets/shimmer.h>
#include <unigui/widgets/skeleton.h>
#include <unigui/widgets/sliderbar.h>
#include <unigui/widgets/sparkline.h>
#include <unigui/widgets/statuslamp.h>
#include <unigui/widgets/taglist.h>
#include <unigui/widgets/timeseries_chart.h>
#include <unigui/widgets/toast.h>
#include <unigui/widgets/togglebutton.h>
#include <unigui/widgets/trayicon.h>
#include <unigui/widgets/virtuallist.h>
#include <unigui/widgets/wizard.h>
