#pragma once

#ifdef _WIN32
    #ifndef NOMINMAX
        #define NOMINMAX
    #endif
    #include <windows.h>
    #define GLFW_EXPOSE_NATIVE_WIN32
#endif

#include <unigui/core/version.h>
#include <unigui/core/context.h>
#include <unigui/core/error.h>
#include <unigui/core/locale.h>
#include <unigui/core/settings.h>
#include <unigui/core/undo_stack.h>
#include <unigui/core/log.h>
#include <unigui/backend/platform_backend.h>
#include <unigui/backend/renderer_backend.h>
#include <unigui/backend/backend_types.h>
#include <unigui/backend/backend_factory.h>
#include <unigui/theme/theme.h>
#include <unigui/theme/style_scope.h>
#include <unigui/widgets/widget_base.h>
#include <unigui/widgets/label.h>
#include <unigui/widgets/button.h>
#include <unigui/widgets/panel.h>
#include <unigui/widgets/form.h>
#include <unigui/widgets/window.h>
#include <unigui/widgets/checkbox.h>
#include <unigui/widgets/slider.h>
#include <unigui/widgets/progressbar.h>
#include <unigui/widgets/radiogroup.h>
#include <unigui/widgets/combobox.h>
#include <unigui/widgets/lineedit.h>
#include <unigui/widgets/groupbox.h>
#include <unigui/widgets/tabwidget.h>
#include <unigui/widgets/treeview.h>
#include <unigui/widgets/listview.h>
#include <unigui/widgets/dialog.h>
#include <unigui/widgets/menubar.h>
#include <unigui/widgets/statusbar.h>
#include <unigui/widgets/toolbar.h>
#include <unigui/widgets/table.h>
#include <unigui/widgets/colorpicker.h>
#include <unigui/widgets/filepath.h>
#include <unigui/widgets/dirpath.h>
#include <unigui/widgets/spinbox.h>
#include <unigui/widgets/toggleswitch.h>
#include <unigui/widgets/inputint.h>
#include <unigui/widgets/inputfloat.h>
#include <unigui/widgets/splitter.h>
#include <unigui/widgets/separator.h>
#include <unigui/widgets/scrollarea.h>
#include <unigui/widgets/tooltip.h>
#include <unigui/widgets/datepicker.h>
#include <unigui/widgets/image.h>
#include <unigui/widgets/loadingindicator.h>
#include <unigui/widgets/notification.h>
#include <unigui/widgets/hyperlink.h>
#include <unigui/widgets/tag.h>
#include <unigui/widgets/breadcrumb.h>
#include <unigui/widgets/multiline.h>
#include <unigui/widgets/iconbutton.h>
#include <unigui/widgets/space.h>
#include <unigui/widgets/contextmenu.h>
#include <unigui/widgets/dragdrop.h>
#include <unigui/widgets/shortcut.h>
#include <unigui/ext/plot.h>
#include <unigui/widgets/virtuallist.h>
#include <unigui/widgets/multicombo.h>
#include <unigui/widgets/propertygrid.h>
#include <unigui/widgets/searchbox.h>
#include <unigui/widgets/toast.h>
#include <unigui/widgets/passwordinput.h>
#include <unigui/widgets/wizard.h>
#include <unigui/app/app.h>
