#include <unigui/core/log.h>
#include <unigui/fonts/font_manager.h>
#include <unigui/theme/color_tokens.h>
#include <unigui/theme/style_tokens.h>
#include <unigui/theme/surface_style.h>
#include <unigui/theme/theme.h>

#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <regex>
#include <sstream>

// Embedded font data (generated by CMake FontEmbed)
#include <jb_mono_font.h>
#ifdef _WIN32
#include <windows.h>
#endif

namespace unigui {

static bool pendingFontRebuild_ = false;
static float pendingFontSize_ = 16.f;
// Opaque backdrop/clear colour for the active theme + surface material. Defaults
// to the Dark window background until the first ApplyTheme() call updates it.
static ImVec4 backdropColor_ = ImVec4(0.10f, 0.10f, 0.12f, 1.00f);

float DetectDPIScale(void* native_window) {
#ifdef _WIN32
    HWND hwnd = (HWND) native_window;
    if (hwnd) {
        // Try per-monitor DPI (Windows 10+)
        using GetDpiForWindow_t = UINT(WINAPI*)(HWND);
        HMODULE user32 = GetModuleHandleA("user32.dll");
        auto pGetDpiForWindow = (GetDpiForWindow_t) GetProcAddress(user32, "GetDpiForWindow");
        if (pGetDpiForWindow) {
            UINT dpi = pGetDpiForWindow(hwnd);
            if (dpi > 0)
                return dpi / 96.0f;
        }
    }
    // Fallback: system DPI
    HDC screen = GetDC(nullptr);
    if (screen) {
        int dpi = GetDeviceCaps(screen, LOGPIXELSX);
        ReleaseDC(nullptr, screen);
        if (dpi > 0)
            return dpi / 96.0f;
    }
#endif
    return 1.0f;
}

void LoadDefaultFont(float size_pixels, const char* ttf_path) {
    auto& io = ImGui::GetIO();
    io.Fonts->Clear();

    ImFontConfig cfg;
    cfg.OversampleH = 2;
    cfg.OversampleV = 2;
    // The embedded blob is a compiled-in static array, NOT heap memory. ImGui must
    // never call free() on it at atlas teardown, or it corrupts the heap and the
    // process dies on shutdown (ImFontAtlas::ClearInputData -> _free_base). Only the
    // file-loaded merge fonts below (IM_ALLOC'd) may be owned by the atlas.
    cfg.FontDataOwnedByAtlas = false;

    // Primary font: embedded JetBrains Mono Nerd Font (always available)
    ImFont* font =
        io.Fonts->AddFontFromMemoryTTF((void*) jb_mono_data, (int) jb_mono_size, size_pixels, &cfg);
    if (font) {
        UNIGUI_LOG_INFO("Font: JetBrains Mono Nerd Font (embedded, {}px)", (int) size_pixels);
    } else {
        // Fallback — should never happen with embedded font
        io.Fonts->AddFontDefault(&cfg);
        io.FontGlobalScale = size_pixels / 13.0f;
        UNIGUI_LOG_WARN("Embedded font failed, using built-in");
        return;
    }

    // Merge glyphs from a system font (optional, platform-specific paths).
    // Build a broad multi-script range so the UI can render Chinese, Japanese,
    // Korean, Cyrillic, Greek, Thai and Vietnamese in addition to Latin.
    cfg.MergeMode = true;
    cfg.FontDataOwnedByAtlas = true; // ImGui frees the data, not us

    static ImVector<ImWchar> s_glyphRanges;
    if (s_glyphRanges.empty()) {
        ImFontGlyphRangesBuilder builder;
        builder.AddRanges(io.Fonts->GetGlyphRangesDefault());     // Basic Latin + Latin-1
        builder.AddRanges(io.Fonts->GetGlyphRangesGreek());       // Greek
        builder.AddRanges(io.Fonts->GetGlyphRangesCyrillic());    // Cyrillic
        builder.AddRanges(io.Fonts->GetGlyphRangesThai());        // Thai
        builder.AddRanges(io.Fonts->GetGlyphRangesVietnamese());  // Vietnamese
        builder.AddRanges(io.Fonts->GetGlyphRangesJapanese());    // Hiragana/Katakana + Kanji
        builder.AddRanges(io.Fonts->GetGlyphRangesKorean());      // Hangul
        builder.AddRanges(io.Fonts->GetGlyphRangesChineseFull()); // CJK Unified Ideographs
        // A few commonly-needed punctuation / symbol blocks.
        static const ImWchar extra[] = {
            0x2000, 0x206F, // General Punctuation (— “ ” … etc.)
            0x20A0, 0x20CF, // Currency Symbols (€ ₿ ₩ …)
            0x2100, 0x214F, // Letterlike Symbols (™ № …)
            0x2190, 0x21FF, // Arrows
            0x2200, 0x22FF, // Mathematical Operators
            0,
        };
        builder.AddRanges(extra);
        builder.BuildRanges(&s_glyphRanges);
    }
    const ImWchar* cjk = s_glyphRanges.Data;

#ifdef _WIN32
    const char* cjk_paths[] = {"C:/Windows/Fonts/msyh.ttc", "C:/Windows/Fonts/simhei.ttf", nullptr};
#elif defined(__APPLE__)
    const char* cjk_paths[] = {"/System/Library/Fonts/PingFang.ttc",
                               "/System/Library/Fonts/STHeiti Light.ttc",
                               "/System/Library/Fonts/AppleSDGothicNeo.ttc", nullptr};
#else // Linux
    const char* cjk_paths[] = {"/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
                               "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
                               "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc", nullptr};
#endif

    for (int i = 0; cjk_paths[i]; i++) {
        FILE* fp = fopen(cjk_paths[i], "rb");
        if (!fp)
            continue;
        fseek(fp, 0, SEEK_END);
        long sz = ftell(fp);
        fseek(fp, 0, SEEK_SET);
        if (sz > 0) {
            void* data = IM_ALLOC(sz);
            fread(data, 1, sz, fp);
            fclose(fp);
            if (io.Fonts->AddFontFromMemoryTTF(data, (int) sz, size_pixels, &cfg, cjk)) {
                UNIGUI_LOG_INFO("CJK font merged: {}", cjk_paths[i]);
                break;
            }
            // Don't IM_FREE — ImGui owns the data now (FontDataOwnedByAtlas=true)
        } else {
            fclose(fp);
        }
    }

    // Load emoji fallback font (platform-specific system emoji)
    fonts::Manager::Instance().LoadSystemEmoji(size_pixels);
}

void BeginTextWrap(float width) {
    if (width <= 0)
        width = ImGui::GetContentRegionAvail().x;
    ImGui::PushTextWrapPos(ImGui::GetCursorPosX() + width);
}
void EndTextWrap() {
    ImGui::PopTextWrapPos();
}

void ApplyTheme(const ThemeConfig& config) {
    using theme::AccentActive;
    using theme::AccentHover;
    using theme::ApplyStyleTokens;
    using theme::WithAlpha;
    auto& io = ImGui::GetIO();
    auto& style = ImGui::GetStyle();
    auto& colors = style.Colors;

    // ── DPI scaling ──────────────────────────────────────────────────────
    float dpi = config.dpi_scale;
    if (dpi <= 0)
        dpi = 1.0f; // caller should have set dpi before calling
    UNIGUI_LOG_INFO("Theme: preset={} surface={} dpi={:.2f} font={}px", (int) config.preset,
                    theme::SurfaceStyleName(config.surface), dpi, (int) (config.font_size * dpi));
    // ── Style base values (shared geometry tokens) ───────────────────────
    // Unified rounding/spacing/border language shared with every theme preset.
    ApplyStyleTokens(style);

    // ── Color palette ────────────────────────────────────────────────────
    if (config.preset == ThemePreset::Dark) {
        // Single source-of-truth accent; hover/active are derived from it.
        const ImVec4 accent = ImVec4(0.40f, 0.58f, 0.93f, 1.00f);
        colors[ImGuiCol_Text] = ImVec4(0.90f, 0.90f, 0.92f, 1.00f);
        colors[ImGuiCol_TextDisabled] = ImVec4(0.50f, 0.50f, 0.55f, 1.00f);
        colors[ImGuiCol_WindowBg] = ImVec4(0.10f, 0.10f, 0.12f, 1.00f);
        colors[ImGuiCol_ChildBg] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_PopupBg] = ImVec4(0.14f, 0.14f, 0.16f, 1.00f);
        colors[ImGuiCol_Border] = ImVec4(0.20f, 0.20f, 0.24f, 1.00f);
        colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[ImGuiCol_FrameBg] = ImVec4(0.16f, 0.16f, 0.18f, 1.00f);
        colors[ImGuiCol_FrameBgHovered] = ImVec4(0.22f, 0.22f, 0.26f, 1.00f);
        colors[ImGuiCol_FrameBgActive] = ImVec4(0.20f, 0.20f, 0.24f, 1.00f);
        colors[ImGuiCol_TitleBg] = ImVec4(0.10f, 0.10f, 0.12f, 1.00f);
        colors[ImGuiCol_TitleBgActive] = ImVec4(0.16f, 0.16f, 0.18f, 1.00f);
        colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.10f, 0.10f, 0.12f, 1.00f);
        colors[ImGuiCol_MenuBarBg] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_ScrollbarBg] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.24f, 0.24f, 0.28f, 1.00f);
        colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.30f, 0.30f, 0.35f, 1.00f);
        colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.35f, 0.35f, 0.40f, 1.00f);
        colors[ImGuiCol_CheckMark] = accent;
        colors[ImGuiCol_SliderGrab] = accent;
        colors[ImGuiCol_SliderGrabActive] = AccentHover(accent);
        colors[ImGuiCol_Button] = ImVec4(0.24f, 0.24f, 0.28f, 1.00f);
        colors[ImGuiCol_ButtonHovered] = ImVec4(0.30f, 0.30f, 0.35f, 1.00f);
        colors[ImGuiCol_ButtonActive] = ImVec4(0.22f, 0.22f, 0.26f, 1.00f);
        colors[ImGuiCol_Header] = ImVec4(0.18f, 0.18f, 0.22f, 1.00f);
        colors[ImGuiCol_HeaderHovered] = ImVec4(0.22f, 0.22f, 0.26f, 1.00f);
        colors[ImGuiCol_HeaderActive] = ImVec4(0.20f, 0.20f, 0.24f, 1.00f);
        colors[ImGuiCol_Separator] = ImVec4(0.20f, 0.20f, 0.24f, 1.00f);
        colors[ImGuiCol_SeparatorHovered] = ImVec4(0.30f, 0.30f, 0.35f, 1.00f);
        colors[ImGuiCol_SeparatorActive] = accent;
        colors[ImGuiCol_ResizeGrip] = ImVec4(0.24f, 0.24f, 0.28f, 1.00f);
        colors[ImGuiCol_ResizeGripHovered] = accent;
        colors[ImGuiCol_ResizeGripActive] = accent;
        colors[ImGuiCol_Tab] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_TabHovered] = ImVec4(0.30f, 0.30f, 0.35f, 1.00f);
        colors[ImGuiCol_TabActive] = ImVec4(0.18f, 0.18f, 0.22f, 1.00f);
        colors[ImGuiCol_TabUnfocused] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_TabUnfocusedActive] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_DockingPreview] = WithAlpha(accent, 0.70f);
        colors[ImGuiCol_DockingEmptyBg] = ImVec4(0.10f, 0.10f, 0.12f, 1.00f);
        colors[ImGuiCol_PlotLines] = accent;
        colors[ImGuiCol_PlotLinesHovered] = ImVec4(1.00f, 0.43f, 0.35f, 1.00f);
        colors[ImGuiCol_PlotHistogram] = accent;
        colors[ImGuiCol_PlotHistogramHovered] = ImVec4(1.00f, 0.43f, 0.35f, 1.00f);
        colors[ImGuiCol_TableHeaderBg] = ImVec4(0.14f, 0.14f, 0.16f, 1.00f);
        colors[ImGuiCol_TableBorderStrong] = ImVec4(0.24f, 0.24f, 0.28f, 1.00f);
        colors[ImGuiCol_TableBorderLight] = ImVec4(0.18f, 0.18f, 0.22f, 1.00f);
        colors[ImGuiCol_TableRowBg] = ImVec4(0.10f, 0.10f, 0.12f, 1.00f);
        colors[ImGuiCol_TableRowBgAlt] = ImVec4(0.12f, 0.12f, 0.14f, 1.00f);
        colors[ImGuiCol_TextSelectedBg] = WithAlpha(accent, 0.35f);
        colors[ImGuiCol_DragDropTarget] = accent;
        colors[ImGuiCol_NavHighlight] = accent;
        colors[ImGuiCol_NavWindowingHighlight] = ImVec4(0.90f, 0.90f, 0.92f, 0.70f);
        colors[ImGuiCol_NavWindowingDimBg] = ImVec4(0.50f, 0.50f, 0.55f, 0.20f);
        colors[ImGuiCol_ModalWindowDimBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.50f);
    } else {
        // Single source-of-truth accent; hover/active are derived from it.
        const ImVec4 accent = ImVec4(0.15f, 0.40f, 0.80f, 1.00f);
        colors[ImGuiCol_Text] = ImVec4(0.15f, 0.15f, 0.18f, 1.00f);
        colors[ImGuiCol_TextDisabled] = ImVec4(0.45f, 0.45f, 0.50f, 1.00f);
        colors[ImGuiCol_WindowBg] = ImVec4(0.96f, 0.96f, 0.97f, 1.00f);
        colors[ImGuiCol_ChildBg] = ImVec4(0.94f, 0.94f, 0.95f, 1.00f);
        colors[ImGuiCol_PopupBg] = ImVec4(0.98f, 0.98f, 0.99f, 1.00f);
        colors[ImGuiCol_Border] = ImVec4(0.72f, 0.72f, 0.76f, 1.00f);
        colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[ImGuiCol_FrameBg] = ImVec4(0.91f, 0.91f, 0.93f, 1.00f);
        colors[ImGuiCol_FrameBgHovered] = ImVec4(0.86f, 0.86f, 0.89f, 1.00f);
        colors[ImGuiCol_FrameBgActive] = ImVec4(0.82f, 0.82f, 0.86f, 1.00f);
        colors[ImGuiCol_TitleBg] = ImVec4(0.90f, 0.90f, 0.92f, 1.00f);
        colors[ImGuiCol_TitleBgActive] = ImVec4(0.82f, 0.82f, 0.85f, 1.00f);
        colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.90f, 0.90f, 0.92f, 1.00f);
        colors[ImGuiCol_MenuBarBg] = ImVec4(0.92f, 0.92f, 0.94f, 1.00f);
        colors[ImGuiCol_ScrollbarBg] = ImVec4(0.94f, 0.94f, 0.95f, 1.00f);
        colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.70f, 0.70f, 0.73f, 1.00f);
        colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.60f, 0.60f, 0.64f, 1.00f);
        colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.50f, 0.50f, 0.55f, 1.00f);
        colors[ImGuiCol_CheckMark] = accent;
        colors[ImGuiCol_SliderGrab] = accent;
        colors[ImGuiCol_SliderGrabActive] = AccentActive(accent);
        colors[ImGuiCol_Button] = ImVec4(0.70f, 0.70f, 0.75f, 1.00f);
        colors[ImGuiCol_ButtonHovered] = ImVec4(0.62f, 0.62f, 0.68f, 1.00f);
        colors[ImGuiCol_ButtonActive] = ImVec4(0.55f, 0.55f, 0.61f, 1.00f);
        colors[ImGuiCol_Header] = ImVec4(0.82f, 0.82f, 0.86f, 1.00f);
        colors[ImGuiCol_HeaderHovered] = ImVec4(0.74f, 0.74f, 0.79f, 1.00f);
        colors[ImGuiCol_HeaderActive] = ImVec4(0.68f, 0.68f, 0.73f, 1.00f);
        colors[ImGuiCol_Separator] = ImVec4(0.72f, 0.72f, 0.76f, 1.00f);
        colors[ImGuiCol_SeparatorHovered] = ImVec4(0.60f, 0.60f, 0.64f, 1.00f);
        colors[ImGuiCol_SeparatorActive] = accent;
        colors[ImGuiCol_ResizeGrip] = ImVec4(0.78f, 0.78f, 0.82f, 1.00f);
        colors[ImGuiCol_ResizeGripHovered] = accent;
        colors[ImGuiCol_ResizeGripActive] = accent;
        colors[ImGuiCol_Tab] = ImVec4(0.88f, 0.88f, 0.90f, 1.00f);
        colors[ImGuiCol_TabHovered] = ImVec4(0.70f, 0.70f, 0.75f, 1.00f);
        colors[ImGuiCol_TabActive] = ImVec4(0.82f, 0.82f, 0.85f, 1.00f);
        colors[ImGuiCol_TabUnfocused] = ImVec4(0.88f, 0.88f, 0.90f, 1.00f);
        colors[ImGuiCol_TabUnfocusedActive] = ImVec4(0.82f, 0.82f, 0.85f, 1.00f);
        colors[ImGuiCol_DockingPreview] = WithAlpha(accent, 0.70f);
        colors[ImGuiCol_DockingEmptyBg] = ImVec4(0.92f, 0.92f, 0.94f, 1.00f);
        colors[ImGuiCol_PlotLines] = accent;
        colors[ImGuiCol_PlotLinesHovered] = ImVec4(0.90f, 0.30f, 0.20f, 1.00f);
        colors[ImGuiCol_PlotHistogram] = accent;
        colors[ImGuiCol_PlotHistogramHovered] = ImVec4(0.90f, 0.30f, 0.20f, 1.00f);
        colors[ImGuiCol_TableHeaderBg] = ImVec4(0.85f, 0.85f, 0.88f, 1.00f);
        colors[ImGuiCol_TableBorderStrong] = ImVec4(0.70f, 0.70f, 0.73f, 1.00f);
        colors[ImGuiCol_TableBorderLight] = ImVec4(0.82f, 0.82f, 0.85f, 1.00f);
        colors[ImGuiCol_TableRowBg] = ImVec4(0.96f, 0.96f, 0.97f, 1.00f);
        colors[ImGuiCol_TableRowBgAlt] = ImVec4(0.92f, 0.92f, 0.94f, 1.00f);
        colors[ImGuiCol_TextSelectedBg] = WithAlpha(accent, 0.35f);
        colors[ImGuiCol_DragDropTarget] = accent;
        colors[ImGuiCol_NavHighlight] = accent;
        colors[ImGuiCol_NavWindowingHighlight] = ImVec4(0.15f, 0.15f, 0.18f, 0.70f);
        colors[ImGuiCol_NavWindowingDimBg] = ImVec4(0.50f, 0.50f, 0.55f, 0.20f);
        colors[ImGuiCol_ModalWindowDimBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.35f);
    }

    // ── Auto-derived table colors (follow theme) ─────────────────────────
    colors[ImGuiCol_TableHeaderBg] =
        ImVec4(colors[ImGuiCol_FrameBg].x * 0.7f, colors[ImGuiCol_FrameBg].y * 0.7f,
               colors[ImGuiCol_FrameBg].z * 0.75f, 1.00f);
    colors[ImGuiCol_TableBorderStrong] =
        ImVec4(colors[ImGuiCol_Border].x * 0.9f, colors[ImGuiCol_Border].y * 0.9f,
               colors[ImGuiCol_Border].z * 0.95f, 1.00f);
    colors[ImGuiCol_TableBorderLight] =
        ImVec4(colors[ImGuiCol_Border].x * 0.7f, colors[ImGuiCol_Border].y * 0.7f,
               colors[ImGuiCol_Border].z * 0.75f, 1.00f);
    // 斑马纹：偶数行 = 窗口底色；奇数行向「文字色」方向混合一定比例，
    // 使深浅行对比更明显（防止在多列可编辑表格里把参数设到错误的行）。
    // 该公式对深色/浅色主题都成立（深色→变亮，浅色→变暗）。
    {
        const ImVec4 wbg = colors[ImGuiCol_WindowBg];
        const ImVec4 txt = colors[ImGuiCol_Text];
        const float kZebra = 0.13f; // 混合比例：越大对比越强
        colors[ImGuiCol_TableRowBg] = ImVec4(wbg.x, wbg.y, wbg.z, 1.00f);
        colors[ImGuiCol_TableRowBgAlt] =
            ImVec4(wbg.x + (txt.x - wbg.x) * kZebra, wbg.y + (txt.y - wbg.y) * kZebra,
                   wbg.z + (txt.z - wbg.z) * kZebra, 1.00f);
    }

    // ── Accent & semantic colour tokens (Step 3) ────────────────────────
    // Re-derive the accent-driven interaction slots (CheckMark/Slider/Separator/
    // ResizeGrip/DragDropTarget/Nav/DockingPreview/TextSelectedBg) from a single
    // base accent so Dark/Light share the exact accent→hover→active relationship,
    // and record the semantic palette (success/warning/danger/info) for widgets.
    theme::ApplyColorTokens(style, theme::AccentFromStyle(style),
                            config.preset == ThemePreset::Dark);

    // ── Surface material (Step 2: glass / solid / frosted / acrylic / minimal) ──
    // Applied after the palette so it composes with any preset; before ScaleAllSizes
    // so its border-size overrides get DPI-scaled with the rest of the geometry.
    theme::ApplySurfaceStyle(style, config.surface);

    // Derive the opaque framebuffer backdrop from the (RGB-stable) window background
    // so translucent glass surfaces read against a tinted background, not black.
    backdropColor_ = theme::BackdropColor(colors[ImGuiCol_WindowBg], config.surface);

    // Scale all sizes by DPI (AFTER setting values so they get scaled)
    style.ScaleAllSizes(dpi);

    // Runtime font size change: defer atlas rebuild (can't do it mid-frame)
    static float lastFontSize = 0.f;
    float targetSize = config.font_size * dpi;
    if (lastFontSize > 0.f && std::abs(targetSize - lastFontSize) > 0.5f) {
        UNIGUI_LOG_INFO("Theme: font size change {}→{}px — queued for next NewFrame",
                        (int) lastFontSize, (int) targetSize);
        pendingFontRebuild_ = true;
        pendingFontSize_ = targetSize;
    }
    lastFontSize = targetSize;
}

bool HasPendingFontRebuild() {
    return pendingFontRebuild_;
}
void ApplyPendingFontRebuild() {
    if (!pendingFontRebuild_)
        return;
    UNIGUI_LOG_INFO("Theme: rebuilding font atlas at {}px", (int) pendingFontSize_);
    auto& io = ImGui::GetIO();
    io.Fonts->Clear();
    LoadDefaultFont(pendingFontSize_, nullptr);
    io.Fonts->Build();
    pendingFontRebuild_ = false;
}

ImVec4 GetBackdropColor() {
    return backdropColor_;
}

static const char* kColorNames[] = {"Text",
                                    "TextDisabled",
                                    "WindowBg",
                                    "ChildBg",
                                    "PopupBg",
                                    "Border",
                                    "BorderShadow",
                                    "FrameBg",
                                    "FrameBgHovered",
                                    "FrameBgActive",
                                    "TitleBg",
                                    "TitleBgActive",
                                    "TitleBgCollapsed",
                                    "MenuBarBg",
                                    "ScrollbarBg",
                                    "ScrollbarGrab",
                                    "ScrollbarGrabHovered",
                                    "ScrollbarGrabActive",
                                    "CheckMark",
                                    "SliderGrab",
                                    "SliderGrabActive",
                                    "Button",
                                    "ButtonHovered",
                                    "ButtonActive",
                                    "Header",
                                    "HeaderHovered",
                                    "HeaderActive",
                                    "Separator",
                                    "SeparatorHovered",
                                    "SeparatorActive",
                                    "ResizeGrip",
                                    "ResizeGripHovered",
                                    "ResizeGripActive",
                                    "Tab",
                                    "TabHovered",
                                    "TabActive",
                                    "TabUnfocused",
                                    "TabUnfocusedActive",
                                    "DockingPreview",
                                    "DockingEmptyBg",
                                    "PlotLines",
                                    "PlotLinesHovered",
                                    "PlotHistogram",
                                    "PlotHistogramHovered",
                                    "TableHeaderBg",
                                    "TableBorderStrong",
                                    "TableBorderLight",
                                    "TableRowBg",
                                    "TableRowBgAlt",
                                    "TextLink",
                                    "TreeLines",
                                    "TextSelectedBg",
                                    "DragDropTarget",
                                    "DragDropTargetBg",
                                    "UnsavedMarker",
                                    "NavCursor",
                                    "NavWindowingHighlight",
                                    "NavWindowingDimBg",
                                    "ModalWindowDimBg"};

std::string ExportThemeJSON() {
    auto& colors = ImGui::GetStyle().Colors;
    constexpr int N = sizeof(kColorNames) / sizeof(kColorNames[0]);
    std::ostringstream ss;
    ss << "{";
    for (int i = 0; i < ImGuiCol_COUNT && i < N; i++) {
        if (i > 0)
            ss << ",";
        ss << "\"" << kColorNames[i] << "\":[" << colors[i].x << "," << colors[i].y << ","
           << colors[i].z << "," << colors[i].w << "]";
    }
    ss << "}";
    return ss.str();
}

bool ImportThemeJSON(const std::string& json) {
    auto& colors = ImGui::GetStyle().Colors;
    constexpr int N = sizeof(kColorNames) / sizeof(kColorNames[0]);
    for (int i = 0; i < ImGuiCol_COUNT && i < N; i++) {
        std::regex re("\"" + std::string(kColorNames[i]) + "\"\\s*:\\s*\\[([^\\]]+)\\]");
        std::smatch m;
        if (std::regex_search(json, m, re)) {
            float vals[4] = {0, 0, 0, 1};
            int vi = 0;
            size_t pos = 0;
            std::string arr = m[1].str();
            while (pos < arr.size() && vi < 4) {
                size_t comma = arr.find(',', pos);
                std::string token =
                    comma != std::string::npos ? arr.substr(pos, comma - pos) : arr.substr(pos);
                char* end = nullptr;
                float v = std::strtof(token.c_str(), &end);
                if (end != token.c_str())
                    vals[vi++] = v;
                pos = comma != std::string::npos ? comma + 1 : arr.size();
            }
            colors[i] = ImVec4(vals[0], vals[1], vals[2], vals[3]);
        }
    }
    return true;
}

} // namespace unigui
